### ISSUE TITLE
Possible to lock Ocramius/PackageVersions dependency?

### ISSUE THREAD

**Issue by MarkVaughn** [Jean85/pretty-package-versions#10]
Ocramius/PackageVersions dropped php 7.2 support. PHP 7.2 is still actively maintained. 
I use this package through phpstan for a ton of my repos. But this breaks at version 1.5 of Ocramius/PackageVersions
https://github.com/Ocramius/PackageVersions/issues/105
Seems a bit radically to suddendly drop support for an active php version.

**Comment by Ocramius** [comment]
As explained in https://github.com/Ocramius/PackageVersions/issues/105:

 > Hey there,
 > 
 > I dropped 7.2 because newer releases are meant for current stable (7.3).
 > 
 > Besides that, previous releases work just as fine :+1:
 > 
 > PHPStan pins to [`jean85/pretty-package-versions:^1.0.3`](https://github.com/phpstan/phpstan/blob/3f2733c0486399efae835897314c205ccbf91b12/composer.json#L10), which locks onto [`"ocramius/package-versions": "^1.2.0"`](https://github.com/Jean85/pretty-package-versions/blob/3c8487fdd6c750ff3f10c32ddfdd2a7803c1d461/composer.json#L7)
 > 
 > That means that your `composer update` should work as fine on PHP 7.1, PHP 7.2 or PHP 7.3.
