### ISSUE TITLE
Support Composer 2 natively

### ISSUE THREAD

**Issue by Jean85** [Jean85/pretty-package-versions#14]
After #13, we support both Composer 1 and 2, but we're forced to rely on the forked dependency to do that. 

We now could release a new version (1.4?) that would require Composer 2, but drop the dependency. In this way, any consumer of this package could still rely on `^1.0` of this package, without tying to a specific Composer version, but having a smooth upgrade path nonetheless, and dropping the additional dependency as soon as possible.

**Comment by Jean85** [comment]
Released as 1.4.

**Comment by Jean85** [comment]
Reopening, since due to #21 I decided to re-release Composer 2 native support as 2.0

**Comment by alexander-schranz** [comment]
@Jean85 any update to this? The follwing issue of sentry https://github.com/getsentry/sentry-symfony/issues/383 does make me problems for me and errors.

**Comment by Jean85** [comment]
I did not have much time in the last months to work on OSS, sorry.

**Comment by alexander-schranz** [comment]
No problem. I invistigated some more time and I'm not sure if its really on your side the issue I linked, as there are 2 composer autoloader loaded the second one override the first one and that makes the problem, that it can not find the version. 

I posted a workaround here: https://github.com/getsentry/sentry-symfony/issues/383#issuecomment-758612849

**Comment by Jean85** [comment]
Closing this as it got released: https://github.com/Jean85/pretty-package-versions/releases/tag/2.0.0
