### ISSUE TITLE
Class 'Composer\InstalledVersions' not found

### ISSUE THREAD

**Issue by saeedtrb** [Jean85/pretty-package-versions#18]
we are using [sentry-laravel](https://github.com/getsentry/sentry-laravel) package which requires your package. 
but after installation we get below error.

`Class 'Composer\InstalledVersions' not found`

we are using `composer.phar` instead of installing composer.

**Comment by Jean85** [comment]
You're installing using `--ignore-platform-reqs`, which skips on checking if a specific requirement of 1.4 is present. That requirement is: https://github.com/Jean85/pretty-package-versions/blob/1fd8d3b809e0d3dd2de20d98b1198d63bf5289a1/composer.json#L7

`composer-runtime-api` is a meta-package that requires using Composer 2.0 (currently in alpha); if you check your platform requirements correctly, you won't be able to install 1.4 (and newer) of this package, and you will obtain a compatible version instead (1.3 more likely).

**Comment by Jean85** [comment]
Closing as stale. Feel free to reply or reopen if this is not resolved.

**Comment by chongshengdz** [comment]
it works fine after upgrading to Composer 2.0+.
Maybe you are using an old version of 1.0+.
'Composer\InstalledVersions' is onl for the Composer 2.0+.

**Comment by abr-rahman** [comment]
Class "Composer\InstalledVersions" not found

**Comment by rajpurohit123** [comment]
Just Simply Run **composer2 install**
