### ISSUE TITLE
Please keep compat with Composer 1 in the foreaseeable future

### ISSUE THREAD

**Issue by nicolas-grekas** [Jean85/pretty-package-versions#21]
Hello, I saw that v1.4 of this package dropped support for Composer 1.

I fear that new features will be added here in the future, but will be made available only to Composer 2 users.

As soon as a dependent will start to require ^1.4 of this package, it means Composer 1 will conflict.

We have the responsibility to make the transition smoother IMHO, thus this issue.

**Comment by Jean85** [comment]
I thought about this issue myself too, after releasing the tag unfortunately.

I think I'll break semver and backport new features in patches under 1.2 or 1.3 if that's the case; do you think it's a good enough solution?

**Comment by nicolas-grekas** [comment]
Another solution is to release v1.5 with support for Composer 1 back.

**Comment by Jean85** [comment]
This would be counter-intuitive for the end user, and I fear could lead to strange behaviors in Composer while resolving deps.

This package is used a lot  as a transitive dependency, and often the end user doesn't have a lot of control over that. So that's why I hesitate to bump it as a new major version.

**Comment by Jean85** [comment]
@nicolas-grekas you made me change my mind. I'll personally PR all our biggest dependants to require `^1.5 || ^2.0` in the future to not have those deps resolving inconsistencies.

WDYT?

**Comment by nicolas-grekas** [comment]
Thanks

**Comment by ArSn** [comment]
Is there any ETA when the 1.5 tag will be released? It is very cool of you to create PRs to your dependents but those have to release new versions themselves (`contentful/core` in our case) or if somebody uses it in a private repository you obviously can not do that for them. 

It breaks our code currently so we will require 1.3 directly for now, which is not a good solution of course.

**Comment by Jean85** [comment]
1.5 released just now: https://github.com/Jean85/pretty-package-versions/releases/tag/1.5.0
