### ISSUE TITLE
Retrieve root package information using native APIs

### ISSUE THREAD

**Issue by Jean85** [Jean85/pretty-package-versions#33]
Currently `getRootPackageVersion` does this: https://github.com/Jean85/pretty-package-versions/blob/6d9ae9a2d9c3a6af0ed65db3205b5d4c03f53f77/src/PrettyVersions.php#L39-L42

This seems dangerous if the user hasn't given a proper name to his project, or if he's using a name that is somehow provided or replaced by some of the installed dependencies. Since the root project name has no effect it the project itself is not a redistributed library, we could leverage the `InstalledVersions::getRootPackage()` API directly to avoid this kind of issue.

This has been originally discovered in https://github.com/getsentry/sentry-symfony/issues/435

**Comment by pkruithof** [comment]
Also, `PrettyVersions::getVersion()` calls `InstalledVersions::getReference($packageName)` which can return `null`: https://github.com/composer/composer/blob/master/src/Composer/InstalledVersions.php#L170, while a `string` is required.

This is the actual code path that produces the fatal error, as I'm sure you're already aware of. But maybe the `getVersion` method should guard against that?

**Comment by Jean85** [comment]
Reference is missing for replaced and provided packages, which 2.0.1 already guard against. I don't know if there are any other situation where that value would still be missing, but I don't think so.

**Comment by Jean85** [comment]
...aaaaand we got the repro case in record time: https://github.com/getsentry/sentry-symfony/issues/435#issuecomment-772343104

[EDIT] FTR, opened #34 to track that.

**Comment by Jean85** [comment]
Fixed in a1cfeec.
