### ISSUE TITLE
Deprecated methods and their replacements

### ISSUE THREAD

**Issue by emodric** [Jean85/pretty-package-versions#37]
Hi!

2.0 version renamed some `*CommitHash` methods to `Version::getReference`, `Version::getShortReference` and `Version::getVersionWithShortReference`.

Would it be possible to add these new methods to 1.5 as a forward compatibility layer?

I require this package as `^1.5 || ^2.0` and what happens is that Psalm reports that I am using a deprecated method, however, there is no way to get rid of the deprecation message (other than ignoring it in Psalm) since those new methods are not available in 1.5.

I hope I am clear enough with my issue :)

Thanks!

**Comment by Jean85** [comment]
Perfectly clear! Yes, I'm sure that we can do that. We could tag that as 1.6, to make it easier to require it correctly.

**Comment by emodric** [comment]
1.6 sounds perfect!

**Comment by Jean85** [comment]
Released in https://github.com/Jean85/pretty-package-versions/releases/tag/1.6.0

**Comment by emodric** [comment]
Thanks @Jean85 !
