### ISSUE TITLE
Root package version generated from the branch name is not pretty

### ISSUE THREAD

**Issue by morozov** [Jean85/pretty-package-versions#4]
Consider the following example:

```bash
git init
cat > composer.json <<EOF
{
    "name": "test/test",
    "require": {
        "jean85/pretty-package-versions": "^1.0.2"
    }
}
EOF

cat > main.php  <<EOF
<?php

require __DIR__ . '/vendor/autoload.php';
echo \Jean85\PrettyVersions::getVersion('test/test')->getPrettyVersion(), PHP_EOL;
EOF

git checkout -b 3.0
git add .
git commit -mTest
composer install
php main.php

# 3.0.9999999.9999999-dev@412b22b
```

The issue is reproducible with the patch from Ocramius/PackageVersions/pull/51 applied. Similarly to #3, it's only reproducible for the root package. For dependencies, the version is displayed without the 9s (e.g. phpunit/phpunit 6.4.x-dev@a94c40a).

Sorry for making so much noise :-) I'm trying to start using pretty versions in a project.

**Comment by Jean85** [comment]
That's really strange. The Composer interface used in https://github.com/Ocramius/PackageVersions/pull/51 says that ` getPrettyVersion()` `Returns the pretty (i.e. non-normalized) version string of this package`, which seems not true here...

I'll try to report this as a bug!

**Comment by Ocramius** [comment]
Handled in Composer 1.5.3 - https://github.com/composer/composer/commit/5ba6d7d4364b0d1898017436935b863d4d8fb14d

**Comment by Jean85** [comment]
Thanks! Closing as resolved, it's unfortunate that I cannot require a Composer version to completely fix this issue; I've added a "Known issue" entry in the changelog about this.
