### ISSUE TITLE
Typo in the about section

### ISSUE THREAD

**Issue by villfa** [Jean85/pretty-package-versions#43]
Hi,

There is a small typo in the _about_ section, `indipendent` instead of `independent`.

![about-typo](https://user-images.githubusercontent.com/2891564/138447863-e6e67b58-f07b-4a05-ab0e-09280e2a2a51.JPG)

**Comment by Jean85** [comment]
Oh you're right, sorry! I got it mixed up with the Italian spelling... Fixed, thank you for reporting it!
