### ISSUE TITLE
ReplacedPackageException thrown for packages that are listen as "replaced", yet not desired

### ISSUE THREAD

**Issue by aedart** [Jean85/pretty-package-versions#45]
I'm experiencing an unexpected behaviour, after upgrading to your `v2.x`. The `ReplacedPackageException` exception is thrown when a target package is listed in the `replace` section of my root `composer.json`. I fail to understand why this is needed...

Thus, when I attempt to obtain the version of one of my packages, e.g. `aedart/athenaeum-console`, from my unit or integration tests, the mentioned exception is thrown.

### Additional Context

I am working on upgrading several packages in my [Athenaeum project](https://github.com/aedart/athenaeum/tree/6.x), which is a mono-repository. As such, all packages that are offered, are listed inside my root `composer.json` in the `replace`section.
E.g.:

```json
{
    "replace": {
        "aedart/athenaeum-acl": "self.version",
        "aedart/athenaeum-audit": "self.version",
        "aedart/athenaeum-circuits": "self.version",
        "aedart/athenaeum-collections": "self.version",
    }
}
``` 
(_Entire `composer.json` content is not shown in the above example._)

The `replace` section is not something that I manually maintain, but rather something that [Monorepo Builder](https://github.com/symplify/monorepo-builder) does for me.

I'm sure that you have a good reason / edge-case when you must throw the mentioned exception, yet I have no idea how to avoid it in my particular case...

**Comment by Jean85** [comment]
Umh that's an interesting corner case. Normally, when replacing, you shouldn't have a clear version available, because in that row of `composer.json` you have a constraint (or often a `*`).

In your case, you're basically proxying toward the root package, so maybe we could handle this in some way. The exceptions are thrown here: https://github.com/Jean85/pretty-package-versions/blob/f6ce0e52c00c810e147c4f7dc6b60abb86e1e195/src/PrettyVersions.php#L61-L76

I would need to dig further on what Composer returns if you set the `replace` with `self.version` but, if that can be intercepted, we could rework and avoid throwing in that case.

Happy to review a PR if you care to open one!

**Comment by aedart** [comment]
Perhaps expand the if statement and check the value if `replace`, that it does not match `self.version` (_or actual version of root package_)?

Yet, before I create a PR for such, I too must understand the inner-works of composer better - do you think that my proposed solution cause issues for someone else?

**Comment by Jean85** [comment]
No I don't, because in other cases it would have thrown the exception.

**Comment by aedart** [comment]
I'll try to spent some time on a PR towards the weekend. In the meantime, I hope someone else reviews this issue and provides some more feedback.

**Comment by aedart** [comment]
Hi @Jean85 

I spent some time trying to understand the core data structure that you use and found that it actually lacks enough meta information. As it stands right now, any proposed solution - changes in your code - would only amount to a strange work-around. Therefore, I have submitted an issue at composer, asking for improvement of the `vendor/composer/installed.php` data structure.
Please review https://github.com/composer/composer/issues/10478, and leave this issue standing, until an appropriate solution has been found at composer (_hopefully the maintainers will agree to either of my proposed solutions_).

**Comment by aedart** [comment]
Hi again.
I have created a PR for composer (https://github.com/composer/composer/pull/10494), which will provide more meta information about replaced and provided packages. I hope they will accept it, because it will be a starting point for solving this edge-case.

**Comment by aedart** [comment]
Sadly, I'm not going to be able to solve this in any good way. I will try to find a different solution.
